### ISSUE TITLE
3D FDFD

### ISSUE THREAD

**Issue by twhughes** [fancompute/ceviche#11]

**Comment by kaipengliuHIT** [comment]
I think there something wrong with the Function make_Dxf and make_Dxb, I think the 'f' should be 'b', and the ‘b’ should be 'f'. These two matrices may be reversed. Or could you tell me what the meaning of make_Dxf? Is it Dex or Dhx in the fdfd_note by R. C. Rumpf?

**Comment by ianwilliamson** [comment]
These are the derivative operators. The "x" in Dxf refers to the derivative along the x-direction and the "f" refers to the operator implementing a "forward" finite difference. The "b" in Dxb refers to the operator implementing a "backward" finite difference.

**Comment by twhughes** [comment]
@kaipengliuHIT As ian said '`Dxf`' is the forward finite difference derivative in x (ie `dE/dx(x, y, z) ~ Dxf * E(x,y,z) = ( E(x+d, y, z) - E(x-d, y, d) ) / 2d`.  From the FDFD notes I linked, these refer to `Dex`.  

Its possible there are differences between our implementation and the notes because we didn't write them strictly following the notes.  However, as long as one is consistent, it shouldn't make a difference whether the forward difference refers to `e` or `h` as long as the other uses the opposite derivative in all cases.

But if you find some specific area where you think our implementation is incorrect please point it out to us and we'll take a look, thanks

**Comment by kaipengliuHIT** [comment]
@twhughes @ianwilliamson Thank you！！！
