### ISSUE TITLE
ceviche.viz.abs Plotting error

### ISSUE THREAD

**Issue by designerguy13-photonics** [fancompute/ceviche#22]
**Describe the bug**
While practicing the inverse design on my workstation where i had pip installed ceviche packages in anaconda3 base environment, I am stuck at a visualization error against the following command referred to first program of workshop.

ceviche.viz.abs(eps_r,cbar=True)

---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-30-086634945a96> in <module>
----> 1 ceviche.viz.abs(eps_r,cbar=True)

E:\anaconda3\lib\site-packages\ceviche\viz.py in abs(val, outline, ax, cbar, cmap, outline_alpha, outline_val)
     32 
     33     vmax = np.abs(val).max()
---> 34     h = ax.imshow(np.abs(val.T), cmap=cmap, origin='lower left', vmin=0, vmax=vmax)
     35 
     36     if outline_val is None and outline is not None: outline_val = 0.5*(outline.min()+outline.max())

E:\anaconda3\lib\site-packages\matplotlib\__init__.py in inner(ax, data, *args, **kwargs)
   1436     def inner(ax, *args, data=None, **kwargs):
   1437         if data is None:
-> 1438             return func(ax, *map(sanitize_sequence, args), **kwargs)
   1439 
   1440         bound = new_sig.bind(ax, *args, **kwargs)

E:\anaconda3\lib\site-packages\matplotlib\axes\_axes.py in imshow(self, X, cmap, norm, aspect, interpolation, alpha, vmin, vmax, origin, extent, filternorm, filterrad, resample, url, **kwargs)
   5517             aspect = rcParams['image.aspect']
   5518         self.set_aspect(aspect)
-> 5519         im = mimage.AxesImage(self, cmap, norm, interpolation, origin, extent,
   5520                               filternorm=filternorm, filterrad=filterrad,
   5521                               resample=resample, **kwargs)

E:\anaconda3\lib\site-packages\matplotlib\image.py in __init__(self, ax, cmap, norm, interpolation, origin, extent, filternorm, filterrad, resample, **kwargs)
    898         self._extent = extent
    899 
--> 900         super().__init__(
    901             ax,
    902             cmap=cmap,

E:\anaconda3\lib\site-packages\matplotlib\image.py in __init__(self, ax, cmap, norm, interpolation, origin, filternorm, filterrad, resample, **kwargs)
    244         if origin is None:
    245             origin = mpl.rcParams['image.origin']
--> 246         cbook._check_in_list(["upper", "lower"], origin=origin)
    247         self.origin = origin
    248         self.set_filternorm(filternorm)

E:\anaconda3\lib\site-packages\matplotlib\cbook\__init__.py in _check_in_list(_values, **kwargs)
   2264     for k, v in kwargs.items():
   2265         if v not in values:
-> 2266             raise ValueError(
   2267                 "{!r} is not a valid value for {}; supported values are {}"
   2268                 .format(v, k, ', '.join(map(repr, values))))

ValueError: 'lower left' is not a valid value for origin; supported values are 'upper', 'lower'

**To Reproduce**

**Expected behavior**

**Desktop (please complete the following information):**
 - OS: [Windows10]
 - Browser [chrome]
 - Version [beta]

**Comment by designerguy13-photonics** [comment]
@twhughes

**Comment by twhughes** [comment]
Based on the error, it seems if you remove the `origin='lower_left'` keword argument on[ this line](https://github.com/fancompute/ceviche/blob/master/ceviche/viz.py#L34) of your source, it should be good to go.

Might be helpful if you post your matplotlib version too, i suspect that it is out of date (or maybe ceviche is not compatible with the newest version)

**Comment by ianwilliamson** [comment]
I think it should be `origin='lower'`. It seems that `'lower left'` has been removed as an option. @designerguy13-photonics please feel free to submit a PR.

**Comment by designerguy13-photonics** [comment]
Hi @ianwilliamson and @twhughes , thanks for the solution. It does worked changing the viz.py file the way you said. 

Also my matplotlib version is 0.33.0

**Comment by designerguy13-photonics** [comment]
Thanks again!

**Comment by twhughes** [comment]
No problem @designerguy13-photonics.
By the way, my `matplotlib.__version__` happens to be '3.2.3'.  You probably want to `pip install --upgrade matplotlib` to avoid further issues like this (and probably the original version of `ceviche` will then work).
