### ISSUE TITLE
Question about eigenmodes of a dielectric waveguide

### ISSUE THREAD

**Issue by tanweihou** [fancompute/ceviche#24]
Hi, I would like to use Ceviche to design a dielectric waveguide.
Its inner layer is dielectric, whereas its outer layer is a conductor, shown in the figure below.
I set it to 10 for illustration purpose.

What is the value permittivity that I should set for a conductor ?
In addition, how should I visualize the mode profile after solving it with `ceviche.modes.get_modes` ?
Thank you very much.
```python
import numpy as np
import matplotlib.pyplot as plt
import ceviche

freq = 300E9
wavelength = 299792458 / freq
omega = 2*np.pi*freq
dl = wavelength / 100
Nx = Ny = 101
Npml = 60
permitivity = 4.41

# Initialize relative permittivity of the domain
epsr = np.ones((Nx, Ny))

xx = np.linspace(-int(Nx/2), int(Nx/2), Nx) * dl
yy = np.linspace(-int(Ny/2), int(Ny/2), Ny) * dl

radius_inner = 450E-6
radius_outer = 500E-6

for idx in range(Nx):
    for idy in range(Ny):
        rr = np.sqrt(xx[idx]**2 + yy[idy]**2)
        if (rr < radius_outer) and (rr >= radius_inner):
            epsr[idx, idy] = permitivity
        if (rr <= radius_conductor) and (rr > radius_outer):
            epsr[idx, idy] = 10

vals, vecs = ceviche.modes.get_modes(epsr, omega, dl, npml=Npml, m=1)
```
![abc(1)](https://user-images.githubusercontent.com/15125658/123211918-b9569780-d489-11eb-814f-a92333a91ac0.png)
![mode(1)](https://user-images.githubusercontent.com/15125658/123211919-b9569780-d489-11eb-87d8-196f51aa4b5a.png)

**Comment by ianwilliamson** [comment]
Ceviche's eigenmode solver only supports 1D geometries (because these correspond to a "slice" of a 2D domain). You won't be able to use it for the case you describe.
