### ISSUE TITLE
Questions on spatial (grid) convergence

### ISSUE THREAD

**Issue by weiliangjinca** [fancompute/ceviche#25]
When I was looking into a simple scenario involving planewave excited by a line source, I noticed that Ceviche somehow requires higher spatial resolution to generate a visibly good planewave. I consider the simplest scenario -- the whole space is vacuum with PML on the y-direction, and periodic in the x-direction. To obtain a good planewave, the pixel size needs to be <lambda/50 for Ceviche, while ~lambda/10 is already good enough for another FDFD software based on Yee-grid without epsilon-averaging. (lambda being the wavelength).

The code is as follows:
`import numpy as np

import matplotlib as mpl
mpl.rcParams['figure.dpi']=100
import matplotlib.pylab as plt

import ceviche
from ceviche.constants import EPSILON_0, C_0, ETA_0

# Source angular frequency in Hz
lam = 1e-6
omega = 2*np.pi*C_0/lam

# Resolution in nm
dl = lam/20

# Simulation domain size in number of pixels
Nx = int(10.*lam/dl)
Ny = Nx

# Initialize relative permittivity of the domain
epsr = np.ones((Nx, Ny))

# Initialize the source position and amplitude
src_x = np.arange(0,Nx-1)
src_y = int(7.5*lam/dl) * np.ones(src_x.shape, dtype=int)
source = np.zeros((Nx, Ny), dtype=np.complex) 
source[src_x, src_y] = 1

# Create the simulation object for 'Ez' (TE) polarization
simulation = ceviche.fdfd_ez(omega, dl, epsr, [0,20],bloch_phases=[0.,0.])
# Run the simulation with the given source
Hx, Hy, Ez = simulation.solve(source)

# Visualize the real value of the Ez field component
ax = ceviche.viz.real(Ez)
# Plot the source position
plt.show()`

For dl=lam/20 as above, the planewave will appear as the attached:
![download](https://user-images.githubusercontent.com/2059907/125541080-6c7feb6a-953e-4dd3-b894-26be2bb8c57d.png)

Is there a particular reason why Ceviche converges slower? Thanks.

**Comment by ianwilliamson** [comment]
Your source is slightly off because you're not filling in all the pixels along the x-axis.

Try this:

```
source[:, src_y] = 1
```

**Comment by weiliangjinca** [comment]
That solves the problem. Thanks for pointing it out.
