### ISSUE TITLE
Complex permittivity support?

### ISSUE THREAD

**Issue by GitHubOpenIssue** [fancompute/ceviche#28]
Hello, I'm not sure if the simulator allows complex permittivity definitions. This feature of material allows to include non linear material as are observers.

If you consider a simple definition in yours examples such as "eps_r=12" to "eps_r=12+2j". Have you got any example that contemplate this feature in other way??  It's because doing this change produces an error

Thank you in advance,

**Comment by GitHubOpenIssue** [comment]
This is example code

> import numpy as np
> 
> import matplotlib as mpl
> mpl.rcParams['figure.dpi']=100
> import matplotlib.pylab as plt
> 
> import ceviche
> 
> # Define simulation parameters (see above)
> omega = 2*np.pi*200e12
> dl = 25e-9
> 
> Nx = 200
> Ny = 80
> Npml = 20
> 
> # Define permittivity for a straight waveguide
> #epsr = np.ones((Nx, Ny))
> epsr = np.ndarray((Nx,Ny), dtype=np.complex128)
> epsr[:,:] = 1+0j
> epsr[:,35:45] = 12+2j
> 
> # Source position and amplitude
> src_y = np.arange(20,60)
> src_x = 30 * np.ones(src_y.shape, dtype=int)
> source = ceviche.modes.insert_mode(omega, dl, src_x, src_y, epsr)
> 
> # Run the simulation for Ez polarization
> simulation = ceviche.fdfd_ez(omega, dl, epsr, [Npml, Npml])
> Hx, Hy, Ez = simulation.solve(source)
> 
> # Visualize the electric field
> ax = ceviche.viz.real(Ez, outline=epsr, cmap='RdBu_r')
> ax.plot(src_x,src_y,'k')
> 
> # Compute the Poynting vector that shows the direction and magnitude of the transferred power
> Sx = -0.5 * np.real(Ez * np.conj(Hy))
> Sy =  0.5 * np.real(Ez * np.conj(Hx))
> 
> # Show the Poynting vector in the x-direction: note the guided power propagation
> ax = ceviche.viz.real(Sx, outline=epsr, cmap='RdBu_r')
> ax.plot(src_x,src_y,'k')
> 
> plt.show()

Thank you very much,

**Comment by ianwilliamson** [comment]
Please properly format your code using a code block. Please also post the error message / stack trace.

**Comment by GitHubOpenIssue** [comment]
Sorry, the code block is this..

```python
import numpy as np

import matplotlib as mpl
mpl.rcParams['figure.dpi']=100
import matplotlib.pylab as plt

import ceviche
#Define simulation parameters (see above)

omega = 2np.pi200e12
dl = 25e-9

Nx = 200
Ny = 80
Npml = 20

#Define permittivity for a straight waveguide

#replaced code
#epsr = np.ones((Nx, Ny))
#epsr[:,35:45] = 12
epsr = np.ndarray((Nx,Ny), dtype=np.complex128)
epsr[:,:] = 1+0j
epsr[:,35:45] = 12+2j

#Source position and amplitude
src_y = np.arange(20,60)
src_x = 30 * np.ones(src_y.shape, dtype=int)
source = ceviche.modes.insert_mode(omega, dl, src_x, src_y, epsr)

#Run the simulation for Ez polarization
simulation = ceviche.fdfd_ez(omega, dl, epsr, [Npml, Npml])
Hx, Hy, Ez = simulation.solve(source)

#Visualize the electric field
ax = ceviche.viz.real(Ez, outline=epsr, cmap='RdBu_r')
ax.plot(src_x,src_y,'k')

#Compute the Poynting vector that shows the direction and magnitude of the transferred power
Sx = -0.5 * np.real(Ez * np.conj(Hy))
Sy = 0.5 * np.real(Ez * np.conj(Hx))

#Show the Poynting vector in the x-direction: note the guided power propagation
ax = ceviche.viz.real(Sx, outline=epsr, cmap='RdBu_r')
ax.plot(src_x,src_y,'k')

plt.show()
```

I only want to confirm your advice. I replaced the code:
```python
epsr = np.ones((Nx, Ny))
epsr[:,35:45] = 12
```
for this:
```python
epsr = np.ndarray((Nx,Ny), dtype=np.complex128)
epsr[:,:] = 1+0j
epsr[:,35:45] = 12+2j
```

It is working. (There is not error message). Is it right?

**Comment by momchilmm** [comment]
The code was initially erroring for me with both real and complex permittivity, but it was not because of the simulation itself but because of the plotting. I downgraded matplotlib to 3.2.0 and then everything runs fine, even with complex permittivity.

Note that complex permittivity does *not* mean nonlinear material. Instead it means gain or loss. In your particular definition, it is gain: 
![image](https://user-images.githubusercontent.com/19151560/198404939-5a6b3909-0f9f-46d5-9d76-dd57f86474c3.png)

To have loss, you need to flip the sign of the imaginary part of the permittivity.

@ianwilliamson the plotting error I got

```
File ~/miniconda3/envs/ceviche/lib/python3.8/site-packages/matplotlib/_api/__init__.py:131, in check_in_list(_values, _print_supported_values, **kwargs)
    129 if _print_supported_values:
    130     msg += f"; supported values are {', '.join(map(repr, values))}"
--> 131 raise ValueError(msg)

ValueError: 'lower left' is not a valid value for origin; supported values are 'upper', 'lower'
```

**Comment by GitHubOpenIssue** [comment]
Thank you very much,
