### ISSUE TITLE
Publish to PyPi

### ISSUE THREAD

**Issue by Jan-David-Black** [fancompute/ceviche#30]
**Is your feature request related to a problem? Please describe.**
The newest bugfixes/compatibility upgrades present in this repository are not present in the current pypi release (v0.1.2) published August 2020.

**Describe the solution you'd like**
Could jou please release the current version of ceviche to pypi

**Describe alternatives you've considered**
Installing directly from github works in most cases with some exceptions. For example publishing a package on pypi with ceviche as dependency.

Thanks for maintaining the project still!!
Regards
JD

**Comment by ianwilliamson** [comment]
@twhughes

**Comment by tylerflex** [comment]
@ianwilliamson twhughes is currently locked out of his account.. but he is totally fine with publishing to pypi. Do you mind either publishing it to pypi yourself or granting me (tylerflex) admin access to ceviche and then I can do it on Monday? Thanks

**Comment by ianwilliamson** [comment]
Latest version (0.1.3) is up on https://pypi.org/project/ceviche/. I had to create the package manually.

I created a workflow configuration for automatically uploading on release, but I don't have the ability to set a token. We might need to coordinate with the person who is currently managing the fancompute GH org for Shanhui's group.

**Comment by twhughes** [comment]
Thanks Ian
